version: '2.3'

services:

  zookeeper:
    image: bitnami/zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  nifi1:
    image: apache/nifi:latest
    container_name: nifi1
    hostname: nifi1
    mem_limit: 2048m
    restart: always
    ports: 
      - 8080:8080 # Unsecured HTTP Web Port
    volumes:
      # Volumes for data input & output
      - ./storeddata/input:/storeddata/input
      - ./storeddata/output:/storeddata/output
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  nifi2:
    image: apache/nifi:latest
    container_name: nifi2
    hostname: nifi2
    mem_limit: 2048m
    restart: always
    ports: 
      - 8081:8080 # Unsecured HTTP Web Port
    volumes:
      # Volumes for data input & output
      - ./storeddata/input:/storeddata/input
      - ./storeddata/output:/storeddata/output
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  nifi3:
    image: apache/nifi:latest
    container_name: nifi3
    hostname: nifi3
    mem_limit: 2048m
    restart: always
    ports: 
      - 8082:8080 # Unsecured HTTP Web Port
    volumes:
      # Volumes for data input & output
      - ./storeddata/input:/storeddata/input
      - ./storeddata/output:/storeddata/output
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_CLUSTER_IS_NODE=true
      - NIFI_CLUSTER_NODE_PROTOCOL_PORT=8082
      - NIFI_ZK_CONNECT_STRING=zookeeper:2181
      - NIFI_ELECTION_MAX_WAIT=1 min
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"