version: '2.3'
services:

  jenkins-master:
    image: jenkins-master:$JENKINS_VERSION
    build:
      context: master/
      args:
        JENKINS_VERSION: $JENKINS_VERSION
        JENKINS_USER: $JENKINS_USER
        JENKINS_PASS: $JENKINS_PASS
    container_name: jenkins-master
    hostname: jenkins-master
    mem_limit: 2048m
    restart: always
    ports:
      - 80:8080
      - 443:443
      - 50000:50000 #build executors port
    volumes:
      - ./master/jenkins_home:/var/jenkins_home
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true -Djenkins.install.runSetupWizard=false"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
  
  jenkins-ssh-slave:
    image: jenkins-ssh-slave:$JENKINS_VERSION
    build:
      context: ssh-slave/
    container_name: jenkins-ssh-slave
    hostname: jenkins-ssh-slave
    mem_limit: 2048m
    restart: always
    ports:
      - '2222:22'
    volumes:
      - ./ssh-slave/home/jenkins:/home/jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    # environment:
    #   SSH_KEY: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC6CPOQDrq...faMvvidd+RVSfDBgJE1g3 jenkins@jenkins.company.tld"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
