version: '2.3'
services:

  flask-server:
    image: flask-server
    build:
      context: .
    container_name: flask-server
    hostname: flask-server
    mem_limit: 1024m
    restart: always
    ports:
      - 5000:5000
    healthcheck:
      test: ps aux | grep "flask run" | grep -v grep || exit 1
      interval: 20s
      timeout: 10s
      retries: 5