version: '2.3'

services:
  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    mem_limit: 2g
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
