version: '2.3'

services:

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    hostname: nifi
    mem_limit: 2048m
    restart: always
    ports: 
      - 8080:8080
    volumes:
      # Volumes for data input & output
      - ./storeddata/input:/storeddata/input
      - ./storeddata/output:/storeddata/output
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"