version: '3.3'

services:
  jenkins:
    image: jenkins/jenkins:2.332.1-lts
    container_name: it-jenkins
    mem_limit: 2048m
    restart: unless-stopped
    # user: root
    expose:
      - 8080
    ports:
      - 50000:50000
    volumes:
      # - ./jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
    networks:
      - jenkins_nw


  nginx:
    image: nginx:latest
    container_name: nginx
    mem_limit: 2048m
    restart: unless-stopped
    links:
      - jenkins
    ports:
      - 80:80
      - 443:443

    volumes:
      - ./certs:/etc/ssl
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - jenkins_nw
    depends_on:
      - jenkins

networks:
  jenkins_nw:
    driver: bridge